# Generated by Django 3.1.2 on 2020-11-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('position', models.CharField(max_length=15, verbose_name='Должность')),
                ('plots', models.CharField(max_length=100, verbose_name='Участки')),
                ('cabinet', models.PositiveIntegerField(verbose_name='Кабинет')),
                ('telephone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('free_time', models.TextField(verbose_name='График работы')),
                ('busy_time', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('oms', models.CharField(max_length=16, verbose_name='Номер ОМС')),
                ('home_adress', models.CharField(max_length=100, verbose_name='Домашний адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('telephone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('appointment_med', models.TextField(blank=True, null=True, verbose_name='Лекарства')),
            ],
        ),
        migrations.CreateModel(
            name='SecondReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.TextField(verbose_name='Назначения')),
                ('appointment_med', models.TextField(verbose_name='Лекарства')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время приема')),
                ('full_name_doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.doctor', verbose_name='ФИО доктора')),
                ('full_name_patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.patient', verbose_name='ФИО пациента')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30, verbose_name='Услуга')),
                ('сomplaints', models.TextField(verbose_name='Жалобы при обращении')),
                ('anamnesis', models.CharField(max_length=30, verbose_name='Анамнез')),
                ('objective_status', models.CharField(max_length=30, verbose_name='Объективный статус')),
                ('appointment', models.TextField(verbose_name='Назначения')),
                ('appointment_med', models.TextField(verbose_name='Лекарства')),
                ('addiction_diseases', models.TextField(verbose_name='Сопутствующие заболевания')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.doctor', verbose_name='Доктор')),
                ('full_name_patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.patient', verbose_name='ФИО пациента')),
            ],
        ),
        migrations.CreateModel(
            name='FirstReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время приема')),
                ('full_name_doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.doctor', verbose_name='ФИО доктора')),
                ('full_name_patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.patient', verbose_name='ФИО пациента')),
            ],
        ),
    ]
