# Generated by Django 3.1.2 on 2020-11-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstreception',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата и время приема'),
        ),
        migrations.AlterField(
            model_name='secondreception',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата и время приема'),
        ),
    ]
