# Generated by Django 3.1.2 on 2020-11-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201113_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=40, verbose_name='ФИО'),
        ),
    ]
