# Generated by Django 3.1.2 on 2020-11-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201115_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstreception',
            name='appointment',
            field=models.TextField(default='', verbose_name='Назначения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstreception',
            name='appointment_med',
            field=models.TextField(default='', verbose_name='Лекарства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstreception',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата и время приема'),
        ),
        migrations.AddField(
            model_name='firstreception',
            name='full_name_doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.doctor', verbose_name='ФИО доктора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstreception',
            name='full_name_patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app.patient', verbose_name='ФИО пациента'),
            preserve_default=False,
        ),
    ]
