# Generated by Django 3.1.2 on 2020-11-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201115_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='interval',
            field=models.TimeField(default='1:00:00', verbose_name='Длина приема'),
        ),
    ]
