# Generated by Django 3.1.2 on 2020-11-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_doctor_interval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstReception',
        ),
    ]
