# Generated by Django 3.1.2 on 2020-11-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_firstreception'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.TextField(verbose_name='Назначения')),
                ('appointment_med', models.TextField(verbose_name='Лекарства')),
                ('datetime', models.DateTimeField(null=True, verbose_name='Дата и время приема')),
                ('full_name_doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.doctor', verbose_name='ФИО доктора')),
                ('full_name_patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.patient', verbose_name='ФИО пациента')),
            ],
        ),
    ]
