# Generated by Django 3.1.2 on 2020-11-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_firstreception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstreception',
            name='appointment',
            field=models.TextField(blank=True, null=True, verbose_name='Назначения'),
        ),
        migrations.AlterField(
            model_name='firstreception',
            name='appointment_med',
            field=models.TextField(blank=True, null=True, verbose_name='Лекарства'),
        ),
        migrations.AlterField(
            model_name='firstreception',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время приема'),
        ),
    ]
