# Generated by Django 3.1.2 on 2020-11-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201116_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
