# Generated by Django 3.1.2 on 2020-11-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_patient_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True, verbose_name='Дата и время приема')),
                ('full_name_doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.doctor', verbose_name='ФИО доктора')),
                ('full_name_patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.patient', verbose_name='ФИО пациента')),
            ],
        ),
        migrations.RemoveField(
            model_name='secondreception',
            name='full_name_doctor',
        ),
        migrations.RemoveField(
            model_name='secondreception',
            name='full_name_patient',
        ),
        migrations.DeleteModel(
            name='FirstReception',
        ),
        migrations.DeleteModel(
            name='SecondReception',
        ),
    ]
